name: annotated_transformers
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.26
  - pandas=2.1
  - jupyterlab
  - ipykernel
  - ipython
  - matplotlib
  - tqdm
  - requests
  - pyyaml
  - spacy=3.5
  - pytorch=2.1
  - torchvision=0.16
  - torchaudio=2.1
  - pytorch-cuda=12.1
  - torchtext=0.16
  - torchdata=0.7
  - pip:
      - altair==5.1.2
      - fsspec==2023.10.0
      - gputil==1.4.0
      - jsonschema==4.19.1
      - jsonschema-specifications==2023.7.1
      - referencing==0.30.2
      - rpds-py==0.10.6
      - toolz==0.12.0
