# a sample conda environment file
# typically named as environment.yml or conda.yml
# this file is used to create a conda environment
# with the specified dependencies, channels, and packages
# to create a conda environment from this file, run the following command
# conda env create -f conda.yml
# to activate the environment, run the following command
# conda activate [name]

name: download_data  # name of the conda environment
channels:  # order matters
  - conda-forge  # loads packages from conda-forge first
  - defaults
dependencies:
  - requests=2.25.1
  - pip=21.0.1
  - mlflow=1.14.1
  - hydra-core=1.0.6
  - pip:
      - wandb==0.10.30
